DROP TABLE utilisateur

CREATE TABLE utilisateur (
[Id] INT IDENTITY (1, 1) NOT NULL,
[LastName] VARCHAR (100) NOT NULL,
[FirstName] VARCHAR (100) NOT NULL,
[Phone] VARCHAR (100) NOT NULL,
PRIMARY KEY CLUSTERED ([Id] ASC)
);
